[build]
  command = "npm run ci"
  publish = "packages/site/dist/"
  functions = "packages/lambda/dist/"

[[redirects]]
  from = "/test/"
  to = "/.netlify/functions/calculate-age"
  status = 200

[[redirects]]
  from = "/get-age-url"
  to = "/.netlify/functions/get-age-url"
  status = 200
